/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC2_DoorLockIndecationAlgo_.c
 * Generated on: Mon Apr 1 2:20:52 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_SWC2_DoorLockIndecationAlgo.h"


extern const Rte_CDS_SWC2_DoorLockIndecationAlgo Rte_Instance_SWC2_DoorLockIndecationAlgo;
extern const Rte_CDS_SWC2_DoorLockIndecationAlgo * const Rte_Inst_SWC2_DoorLockIndecationAlgo;


extern Std_ReturnType SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Buffer_retcode;

extern FunctionPtr_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led Rte_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_SWC2_DoorLockIndecationAlgo_Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState(myuint8 DoorState)
{
	(Rte_Inst_SWC2_DoorLockIndecationAlgo)->Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState->value = DoorState;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_SWC2_DoorLockIndecationAlgo_Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState(void)
{
	return &(Rte_Inst_SWC2_DoorLockIndecationAlgo)->Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_SWC2_DoorLockIndecationAlgo_Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState(void)
{
	return (Rte_Inst_SWC2_DoorLockIndecationAlgo)->Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState->value;
}
DECLSPEC_EXPORT void ARUnit_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_ReturnCode(Std_ReturnType returnCode)
{
	SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Delegate(FunctionPtr_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led  delegate)
{
	Rte_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_SWC2_DoorLockIndecationAlgo_Run_DoorLockAlgo(void)
{
	Run_DoorLockAlgo();
}
