/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_SWC1_DoorLockIndecation.h
 * Generated on: Mon Apr 1 2:20:52 EET
 ********************************************************************/

#include "Rte_SWC1_DoorLockIndecation.h"	

#ifndef ARUNIT_SWC1_DOORLOCKINDECATION_H
#define ARUNIT_SWC1_DOORLOCKINDECATION_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState(myuint8 DoorState);
DECLSPEC_EXPORT myuint8 ARUnit_IRead_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState(void);
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_SWC1_DoorLockIndecation_Run_Led(myuint8 LedState);

DECLSPEC_EXPORT void ARUnit_Trigger_SWC1_DoorLockIndecation_Run_ReadDoorSensor(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_SWC1_DOORLOCKINDECATION_H */
