/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC2_DoorLockIndecationAlgo_.c
 * Generated on: Mon Apr 1 2:20:52 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SWC2_DoorLockIndecationAlgo.h"


Rte_DE_myuint8 Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState;


const Rte_CDS_SWC2_DoorLockIndecationAlgo Rte_Instance_SWC2_DoorLockIndecationAlgo = {
&Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState
};

const Rte_CDS_SWC2_DoorLockIndecationAlgo * const Rte_Inst_SWC2_DoorLockIndecationAlgo = &Rte_Instance_SWC2_DoorLockIndecationAlgo;


Std_ReturnType SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Buffer_retcode = RTE_E_OK;

FunctionPtr_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led Rte_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Delegate = 0;

myuint8 Rte_IRead_SWC2_DoorLockIndecationAlgo_Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState (void)
{
	return (Rte_Inst_SWC2_DoorLockIndecationAlgo)->Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState->value;
}
Std_ReturnType Rte_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led (myuint8 LedState)
{
	Std_ReturnType __result = SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Buffer_retcode;
	if ( Rte_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Delegate != 0 ) {
		__result = Rte_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led_Delegate(LedState);
	}
	return __result;
}
