/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC2_DoorLockIndecationAlgo.h
 * Generated on: Mon Apr 1 2:20:52 EET
 ********************************************************************/

#ifndef RTE_SWC2_DOORLOCKINDECATIONALGO_H
#define RTE_SWC2_DOORLOCKINDECATIONALGO_H

#include "Rte_SWC2_DoorLockIndecationAlgo_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC2_DoorLockIndecationAlgo * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC2_DoorLockIndecationAlgo * const Rte_Inst_SWC2_DoorLockIndecationAlgo;

/************************ application errors *************************/

#define RTE_E_ClServInterface_Led_ERROR_OK ((Std_ReturnType)0)
#define RTE_E_ClServInterface_Led_ERROR_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		ReqPort_SendRec_DoorState
 * Interface:	SendRecInterface_DoorState
 * DataElement:	DoorState
 * Runnable:	Run_DoorLockAlgo
 *****************************************************/
extern myuint8 Rte_IRead_SWC2_DoorLockIndecationAlgo_Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState (void);
#ifndef IN_RTE_C
#define Rte_IRead_Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState() \
	Rte_IRead_SWC2_DoorLockIndecationAlgo_Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState()
#endif

/*****************************************************
 * Port: 		ReqPort_ClServInterface_Led
 * Interface:	ClServInterface_Led
 * Operation:	Led
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led (myuint8 LedState);
#ifndef IN_RTE_C
#define Rte_Call_ReqPort_ClServInterface_Led_Led(LedState) \
	Rte_Call_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led(LedState)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Run_DoorLockAlgo
 * Period:		0.012
 *****************************************************/
extern void Run_DoorLockAlgo(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_SWC2_DoorLockIndecationAlgo_ReqPort_ClServInterface_Led_Led)(myuint8 LedState);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC2_DOORLOCKINDECATIONALGO_H */
