/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC1_DoorLockIndecation_Type.h
 * Generated on: Mon Apr 1 2:20:52 EET
 ********************************************************************/

#ifndef RTE_SWC1_DOORLOCKINDECATION_TYPE_H
#define RTE_SWC1_DOORLOCKINDECATION_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define myuint8_LowerLimit  (0U)
#define myuint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC1_DOORLOCKINDECATION_TYPE_H */
