/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC1_DoorLockIndecation.h
 * Generated on: Mon Apr 1 2:20:52 EET
 ********************************************************************/

#ifndef RTE_SWC1_DOORLOCKINDECATION_H
#define RTE_SWC1_DOORLOCKINDECATION_H

#include "Rte_SWC1_DoorLockIndecation_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC1_DoorLockIndecation * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC1_DoorLockIndecation * const Rte_Inst_SWC1_DoorLockIndecation;

/************************ application errors *************************/

#define RTE_E_ClServInterface_Led_ERROR_OK ((Std_ReturnType)0)
#define RTE_E_ClServInterface_Led_ERROR_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		ProvPort_SendRec_DoorState
 * Interface:	SendRecInterface_DoorState
 * DataElement:	DoorState
 * Runnable:	Run_ReadDoorSensor
 *****************************************************/
extern void Rte_IWrite_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState (myuint8 DoorState);
#ifndef IN_RTE_C
#define Rte_IWrite_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState(RTEData) \
	Rte_IWrite_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState(RTEData)
#endif
extern myuint8* Rte_IWriteRef_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState() \
	Rte_IWriteRef_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState()
#endif

/*****************************************************
 * Port: 		ProvPort_ClServInterface_Led
 * Interface:	ClServInterface_Led
 * Operation:	Led
 *****************************************************/
extern Std_ReturnType Run_Led(myuint8 LedState) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Run_ReadDoorSensor
 * Period:		0.01
 *****************************************************/
extern void Run_ReadDoorSensor(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC1_DOORLOCKINDECATION_H */
