/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC1_DoorLockIndecation_.c
 * Generated on: Mon Apr 1 2:20:52 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SWC1_DoorLockIndecation.h"


Rte_DE_myuint8 Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState;


const Rte_CDS_SWC1_DoorLockIndecation Rte_Instance_SWC1_DoorLockIndecation = {
&Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState
};

const Rte_CDS_SWC1_DoorLockIndecation * const Rte_Inst_SWC1_DoorLockIndecation = &Rte_Instance_SWC1_DoorLockIndecation;




void Rte_IWrite_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState (myuint8 DoorState)
{
	(Rte_Inst_SWC1_DoorLockIndecation)->Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState->value = DoorState;
}
myuint8* Rte_IWriteRef_SWC1_DoorLockIndecation_Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState(void)
{
	return &(Rte_Inst_SWC1_DoorLockIndecation)->Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState->value;
}
