/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Mon Apr 1 2:20:52 EET
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/

typedef unsigned char myuint8;


/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/

typedef struct {
	myuint8 value;
} Rte_DE_myuint8;


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: SWC1_DoorLockIndecation 
 *********************************************************************/
typedef struct Rte_CDS_SWC1_DoorLockIndecation
{
	/* Data Handles section*/
	Rte_DE_myuint8 *Run_ReadDoorSensor_ProvPort_SendRec_DoorState_DoorState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SWC1_DoorLockIndecation;

/*********************************************************************
 * component data structure for SWC: SWC2_DoorLockIndecationAlgo 
 *********************************************************************/
typedef struct Rte_CDS_SWC2_DoorLockIndecationAlgo
{
	/* Data Handles section*/
	Rte_DE_myuint8 *Run_DoorLockAlgo_ReqPort_SendRec_DoorState_DoorState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SWC2_DoorLockIndecationAlgo;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
